export enum EffectCommandType {
    Arpeggio = 0,
    PortamentoUp = 1,
    PortamentoDown = 2,
    TonePortamento = 3,
    Vibrato = 4,
    SetMasterVolume = 5,
    CallRoutine = 6,
    NoteDelay = 7,
    SetPanning = 8,
    SetDutyCycle = 9,
    VolumeSlide = 10,
    PositionJump = 11,
    SetVolume = 12,
    PatternBreak = 13,
    NoteCut = 14,
    SetSpeed = 15,
}
