import { nls } from '@theia/core';
import React, { useContext } from 'react';
import { GRAPHICAL_EDITOR_FOCUS_CONTEXT } from '../../../ves-editors-context-key-service';
import { EditorsContext, EditorsContextType } from '../../../ves-editors-types';
import VContainer from '../../Common/Base/VContainer';
import ButtonAssignment from '../../Common/ButtonAssignment/ButtonAssignment';
import { SoundEditorCommands } from '../SoundEditorCommands';

interface KeybindingsProps {
}

export default function Keybindings(props: KeybindingsProps): React.JSX.Element {
    const { services } = useContext(EditorsContext) as EditorsContextType;
    const KEYBINDING_WIDTH = 420;

    return (
        <VContainer gap={10}>
            <label>
                {nls.localize('vuengine/editors/sound/general', 'General')}
            </label>
            <VContainer>
                <ButtonAssignment
                    command={SoundEditorCommands.PLAY_PAUSE}
                    vesKeybindingService={services.vesKeybindingService}
                    when={GRAPHICAL_EDITOR_FOCUS_CONTEXT}
                    width={KEYBINDING_WIDTH}
                />
                <ButtonAssignment
                    command={SoundEditorCommands.STOP}
                    vesKeybindingService={services.vesKeybindingService}
                    when={GRAPHICAL_EDITOR_FOCUS_CONTEXT}
                    width={KEYBINDING_WIDTH}
                />
                <ButtonAssignment
                    command={SoundEditorCommands.TOGGLE_EVENT_LIST_VISIBILITY}
                    vesKeybindingService={services.vesKeybindingService}
                    when={GRAPHICAL_EDITOR_FOCUS_CONTEXT}
                    width={KEYBINDING_WIDTH}
                />
                <ButtonAssignment
                    command={SoundEditorCommands.TOGGLE_SEQUENCER_VISIBILITY}
                    vesKeybindingService={services.vesKeybindingService}
                    when={GRAPHICAL_EDITOR_FOCUS_CONTEXT}
                    width={KEYBINDING_WIDTH}
                />
                <ButtonAssignment
                    command={SoundEditorCommands.TOGGLE_EFFECTS_PANEL_VISIBILITY}
                    vesKeybindingService={services.vesKeybindingService}
                    when={GRAPHICAL_EDITOR_FOCUS_CONTEXT}
                    width={KEYBINDING_WIDTH}
                />
                <ButtonAssignment
                    command={SoundEditorCommands.TOGGLE_SIDEBAR_VISIBILITY}
                    vesKeybindingService={services.vesKeybindingService}
                    when={GRAPHICAL_EDITOR_FOCUS_CONTEXT}
                    width={KEYBINDING_WIDTH}
                />
                <ButtonAssignment
                    command={SoundEditorCommands.OPEN_INSTRUMENT_EDITOR}
                    vesKeybindingService={services.vesKeybindingService}
                    when={GRAPHICAL_EDITOR_FOCUS_CONTEXT}
                    width={KEYBINDING_WIDTH}
                />
            </VContainer>
            <label>
                {nls.localize('vuengine/editors/sound/utilities', 'Utilities')}
            </label>
            <VContainer>
                <VContainer>
                    <ButtonAssignment
                        command={SoundEditorCommands.IMPORT}
                        vesKeybindingService={services.vesKeybindingService}
                    when={GRAPHICAL_EDITOR_FOCUS_CONTEXT}
                        width={KEYBINDING_WIDTH}
                    />
                    <ButtonAssignment
                        command={SoundEditorCommands.EXPORT}
                        vesKeybindingService={services.vesKeybindingService}
                    when={GRAPHICAL_EDITOR_FOCUS_CONTEXT}
                        width={KEYBINDING_WIDTH}
                    />
                    <ButtonAssignment
                        command={SoundEditorCommands.TRANSPOSE}
                        vesKeybindingService={services.vesKeybindingService}
                    when={GRAPHICAL_EDITOR_FOCUS_CONTEXT}
                        width={KEYBINDING_WIDTH}
                    />
                    <ButtonAssignment
                        command={SoundEditorCommands.REMOVE_UNUSED_PATTERNS}
                        vesKeybindingService={services.vesKeybindingService}
                    when={GRAPHICAL_EDITOR_FOCUS_CONTEXT}
                        width={KEYBINDING_WIDTH}
                    />
                    <ButtonAssignment
                        command={SoundEditorCommands.REMOVE_UNUSED_INSTRUMENTS}
                        vesKeybindingService={services.vesKeybindingService}
                    when={GRAPHICAL_EDITOR_FOCUS_CONTEXT}
                        width={KEYBINDING_WIDTH}
                    />
                    <ButtonAssignment
                        command={SoundEditorCommands.CLEAN_DUPLICATE_PATTERNS}
                        vesKeybindingService={services.vesKeybindingService}
                    when={GRAPHICAL_EDITOR_FOCUS_CONTEXT}
                        width={KEYBINDING_WIDTH}
                    />
                </VContainer>
            </VContainer>
            <label>
                {nls.localize('vuengine/editors/sound/options', 'Options')}
            </label>
            <VContainer>
                <ButtonAssignment
                    command={SoundEditorCommands.TOOL_EDIT}
                    vesKeybindingService={services.vesKeybindingService}
                    when={GRAPHICAL_EDITOR_FOCUS_CONTEXT}
                    width={KEYBINDING_WIDTH}
                />
                <ButtonAssignment
                    command={SoundEditorCommands.TOOL_ERASER}
                    vesKeybindingService={services.vesKeybindingService}
                    when={GRAPHICAL_EDITOR_FOCUS_CONTEXT}
                    width={KEYBINDING_WIDTH}
                />
                <ButtonAssignment
                    command={SoundEditorCommands.TOOL_DRAG}
                    vesKeybindingService={services.vesKeybindingService}
                    when={GRAPHICAL_EDITOR_FOCUS_CONTEXT}
                    width={KEYBINDING_WIDTH}
                />
                <ButtonAssignment
                    command={SoundEditorCommands.TOOL_MARQUEE}
                    vesKeybindingService={services.vesKeybindingService}
                    when={GRAPHICAL_EDITOR_FOCUS_CONTEXT}
                    width={KEYBINDING_WIDTH}
                />
                <ButtonAssignment
                    command={SoundEditorCommands.TOOL_MARQUEE_MODE_REPLACE}
                    vesKeybindingService={services.vesKeybindingService}
                    when={GRAPHICAL_EDITOR_FOCUS_CONTEXT}
                    width={KEYBINDING_WIDTH}
                />
                <ButtonAssignment
                    command={SoundEditorCommands.TOOL_MARQUEE_MODE_ADD}
                    vesKeybindingService={services.vesKeybindingService}
                    when={GRAPHICAL_EDITOR_FOCUS_CONTEXT}
                    width={KEYBINDING_WIDTH}
                />
                <ButtonAssignment
                    command={SoundEditorCommands.TOOL_MARQUEE_MODE_SUBTRACT}
                    vesKeybindingService={services.vesKeybindingService}
                    when={GRAPHICAL_EDITOR_FOCUS_CONTEXT}
                    width={KEYBINDING_WIDTH}
                />
                <ButtonAssignment
                    command={SoundEditorCommands.TOGGLE_NOTE_SNAPPING}
                    vesKeybindingService={services.vesKeybindingService}
                    when={GRAPHICAL_EDITOR_FOCUS_CONTEXT}
                    width={KEYBINDING_WIDTH}
                />
                <ButtonAssignment
                    command={SoundEditorCommands.SET_NOTE_LENGTH_1}
                    vesKeybindingService={services.vesKeybindingService}
                    when={GRAPHICAL_EDITOR_FOCUS_CONTEXT}
                    width={KEYBINDING_WIDTH}
                />
                <ButtonAssignment
                    command={SoundEditorCommands.SET_NOTE_LENGTH_2}
                    vesKeybindingService={services.vesKeybindingService}
                    when={GRAPHICAL_EDITOR_FOCUS_CONTEXT}
                    width={KEYBINDING_WIDTH}
                />
                <ButtonAssignment
                    command={SoundEditorCommands.SET_NOTE_LENGTH_4}
                    vesKeybindingService={services.vesKeybindingService}
                    when={GRAPHICAL_EDITOR_FOCUS_CONTEXT}
                    width={KEYBINDING_WIDTH}
                />
                <ButtonAssignment
                    command={SoundEditorCommands.SET_NOTE_LENGTH_8}
                    vesKeybindingService={services.vesKeybindingService}
                    when={GRAPHICAL_EDITOR_FOCUS_CONTEXT}
                    width={KEYBINDING_WIDTH}
                />
                <ButtonAssignment
                    command={SoundEditorCommands.SET_NOTE_LENGTH_16}
                    vesKeybindingService={services.vesKeybindingService}
                    when={GRAPHICAL_EDITOR_FOCUS_CONTEXT}
                    width={KEYBINDING_WIDTH}
                />
            </VContainer>
            <label>
                {nls.localize('vuengine/editors/sound/sequencer', 'Sequencer')}
            </label>
            <VContainer>
                <ButtonAssignment
                    command={SoundEditorCommands.ADD_TRACK}
                    vesKeybindingService={services.vesKeybindingService}
                    when={GRAPHICAL_EDITOR_FOCUS_CONTEXT}
                    width={KEYBINDING_WIDTH}
                />
                <ButtonAssignment
                    command={SoundEditorCommands.ADD_PATTERN}
                    vesKeybindingService={services.vesKeybindingService}
                    when={GRAPHICAL_EDITOR_FOCUS_CONTEXT}
                    width={KEYBINDING_WIDTH}
                />
                <ButtonAssignment
                    command={SoundEditorCommands.REMOVE_SELECTED_NOTES_OR_PATTERNS}
                    vesKeybindingService={services.vesKeybindingService}
                    when={GRAPHICAL_EDITOR_FOCUS_CONTEXT}
                    width={KEYBINDING_WIDTH}
                />
                <ButtonAssignment
                    command={SoundEditorCommands.SELECT_TRACK_1}
                    vesKeybindingService={services.vesKeybindingService}
                    when={GRAPHICAL_EDITOR_FOCUS_CONTEXT}
                    width={KEYBINDING_WIDTH}
                />
                <ButtonAssignment
                    command={SoundEditorCommands.SELECT_TRACK_2}
                    vesKeybindingService={services.vesKeybindingService}
                    when={GRAPHICAL_EDITOR_FOCUS_CONTEXT}
                    width={KEYBINDING_WIDTH}
                />
                <ButtonAssignment
                    command={SoundEditorCommands.SELECT_TRACK_3}
                    vesKeybindingService={services.vesKeybindingService}
                    when={GRAPHICAL_EDITOR_FOCUS_CONTEXT}
                    width={KEYBINDING_WIDTH}
                />
                <ButtonAssignment
                    command={SoundEditorCommands.SELECT_TRACK_4}
                    vesKeybindingService={services.vesKeybindingService}
                    when={GRAPHICAL_EDITOR_FOCUS_CONTEXT}
                    width={KEYBINDING_WIDTH}
                />
                <ButtonAssignment
                    command={SoundEditorCommands.SELECT_TRACK_5}
                    vesKeybindingService={services.vesKeybindingService}
                    when={GRAPHICAL_EDITOR_FOCUS_CONTEXT}
                    width={KEYBINDING_WIDTH}
                />
                <ButtonAssignment
                    command={SoundEditorCommands.SELECT_TRACK_6}
                    vesKeybindingService={services.vesKeybindingService}
                    when={GRAPHICAL_EDITOR_FOCUS_CONTEXT}
                    width={KEYBINDING_WIDTH}
                />
                <ButtonAssignment
                    command={SoundEditorCommands.SELECT_NEXT_TRACK}
                    vesKeybindingService={services.vesKeybindingService}
                    when={GRAPHICAL_EDITOR_FOCUS_CONTEXT}
                    width={KEYBINDING_WIDTH}
                />
                <ButtonAssignment
                    command={SoundEditorCommands.SELECT_PREVIOUS_TRACK}
                    vesKeybindingService={services.vesKeybindingService}
                    when={GRAPHICAL_EDITOR_FOCUS_CONTEXT}
                    width={KEYBINDING_WIDTH}
                />
                <ButtonAssignment
                    command={SoundEditorCommands.SELECT_NEXT_PATTERN}
                    vesKeybindingService={services.vesKeybindingService}
                    when={GRAPHICAL_EDITOR_FOCUS_CONTEXT}
                    width={KEYBINDING_WIDTH}
                />
                <ButtonAssignment
                    command={SoundEditorCommands.SELECT_PREVIOUS_PATTERN}
                    vesKeybindingService={services.vesKeybindingService}
                    when={GRAPHICAL_EDITOR_FOCUS_CONTEXT}
                    width={KEYBINDING_WIDTH}
                />
                <ButtonAssignment
                    command={SoundEditorCommands.SEQUENCER_VERTICAL_SCALE_REDUCE}
                    vesKeybindingService={services.vesKeybindingService}
                    when={GRAPHICAL_EDITOR_FOCUS_CONTEXT}
                    width={KEYBINDING_WIDTH}
                />
                <ButtonAssignment
                    command={SoundEditorCommands.SEQUENCER_VERTICAL_SCALE_INCREASE}
                    vesKeybindingService={services.vesKeybindingService}
                    when={GRAPHICAL_EDITOR_FOCUS_CONTEXT}
                    width={KEYBINDING_WIDTH}
                />
                <ButtonAssignment
                    command={SoundEditorCommands.SEQUENCER_VERTICAL_SCALE_RESET}
                    vesKeybindingService={services.vesKeybindingService}
                    when={GRAPHICAL_EDITOR_FOCUS_CONTEXT}
                    width={KEYBINDING_WIDTH}
                />
                <ButtonAssignment
                    command={SoundEditorCommands.SEQUENCER_HORIZONTAL_SCALE_REDUCE}
                    vesKeybindingService={services.vesKeybindingService}
                    when={GRAPHICAL_EDITOR_FOCUS_CONTEXT}
                    width={KEYBINDING_WIDTH}
                />
                <ButtonAssignment
                    command={SoundEditorCommands.SEQUENCER_HORIZONTAL_SCALE_INCREASE}
                    vesKeybindingService={services.vesKeybindingService}
                    when={GRAPHICAL_EDITOR_FOCUS_CONTEXT}
                    width={KEYBINDING_WIDTH}
                />
                <ButtonAssignment
                    command={SoundEditorCommands.SEQUENCER_HORIZONTAL_SCALE_RESET}
                    vesKeybindingService={services.vesKeybindingService}
                    when={GRAPHICAL_EDITOR_FOCUS_CONTEXT}
                    width={KEYBINDING_WIDTH}
                />
            </VContainer>
            <label>
                {nls.localize('vuengine/editors/sound/pianoRoll', 'Piano Roll')}
            </label>
            <VContainer>
                <ButtonAssignment
                    command={SoundEditorCommands.PIANO_ROLL_SELECT_NEXT_STEP}
                    vesKeybindingService={services.vesKeybindingService}
                    when={GRAPHICAL_EDITOR_FOCUS_CONTEXT}
                    width={KEYBINDING_WIDTH}
                />
                <ButtonAssignment
                    command={SoundEditorCommands.PIANO_ROLL_SELECT_PREVIOUS_STEP}
                    vesKeybindingService={services.vesKeybindingService}
                    when={GRAPHICAL_EDITOR_FOCUS_CONTEXT}
                    width={KEYBINDING_WIDTH}
                />
                <ButtonAssignment
                    command={SoundEditorCommands.PIANO_ROLL_SELECT_NEXT_NOTE}
                    vesKeybindingService={services.vesKeybindingService}
                    when={GRAPHICAL_EDITOR_FOCUS_CONTEXT}
                    width={KEYBINDING_WIDTH}
                />
                <ButtonAssignment
                    command={SoundEditorCommands.PIANO_ROLL_SELECT_PREVIOUS_NOTE}
                    vesKeybindingService={services.vesKeybindingService}
                    when={GRAPHICAL_EDITOR_FOCUS_CONTEXT}
                    width={KEYBINDING_WIDTH}
                />
                <ButtonAssignment
                    command={SoundEditorCommands.SELECT_AT_CURSOR_POSITION}
                    vesKeybindingService={services.vesKeybindingService}
                    when={GRAPHICAL_EDITOR_FOCUS_CONTEXT}
                    width={KEYBINDING_WIDTH}
                />
                <ButtonAssignment
                    command={SoundEditorCommands.ADD_AT_CURSOR_POSITION}
                    vesKeybindingService={services.vesKeybindingService}
                    when={GRAPHICAL_EDITOR_FOCUS_CONTEXT}
                    width={KEYBINDING_WIDTH}
                />
                <ButtonAssignment
                    command={SoundEditorCommands.SELECT_ALL_NOTES}
                    vesKeybindingService={services.vesKeybindingService}
                    when={GRAPHICAL_EDITOR_FOCUS_CONTEXT}
                    width={KEYBINDING_WIDTH}
                />
                <ButtonAssignment
                    command={SoundEditorCommands.REMOVE_SELECTED_NOTES_OR_PATTERNS}
                    vesKeybindingService={services.vesKeybindingService}
                    when={GRAPHICAL_EDITOR_FOCUS_CONTEXT}
                    width={KEYBINDING_WIDTH}
                />
                <ButtonAssignment
                    command={SoundEditorCommands.COPY_SELECTION}
                    vesKeybindingService={services.vesKeybindingService}
                    when={GRAPHICAL_EDITOR_FOCUS_CONTEXT}
                    width={KEYBINDING_WIDTH}
                />
                <ButtonAssignment
                    command={SoundEditorCommands.CUT_SELECTION}
                    vesKeybindingService={services.vesKeybindingService}
                    when={GRAPHICAL_EDITOR_FOCUS_CONTEXT}
                    width={KEYBINDING_WIDTH}
                />
                <ButtonAssignment
                    command={SoundEditorCommands.PASTE_SELECTION}
                    vesKeybindingService={services.vesKeybindingService}
                    when={GRAPHICAL_EDITOR_FOCUS_CONTEXT}
                    width={KEYBINDING_WIDTH}
                />
                <ButtonAssignment
                    command={SoundEditorCommands.NOTES_UP}
                    vesKeybindingService={services.vesKeybindingService}
                    when={GRAPHICAL_EDITOR_FOCUS_CONTEXT}
                    width={KEYBINDING_WIDTH}
                />
                <ButtonAssignment
                    command={SoundEditorCommands.NOTES_DOWN}
                    vesKeybindingService={services.vesKeybindingService}
                    when={GRAPHICAL_EDITOR_FOCUS_CONTEXT}
                    width={KEYBINDING_WIDTH}
                />
                <ButtonAssignment
                    command={SoundEditorCommands.NOTES_UP_AN_OCTAVE}
                    vesKeybindingService={services.vesKeybindingService}
                    when={GRAPHICAL_EDITOR_FOCUS_CONTEXT}
                    width={KEYBINDING_WIDTH}
                />
                <ButtonAssignment
                    command={SoundEditorCommands.NOTES_DOWN_AN_OCTAVE}
                    vesKeybindingService={services.vesKeybindingService}
                    when={GRAPHICAL_EDITOR_FOCUS_CONTEXT}
                    width={KEYBINDING_WIDTH}
                />
                <ButtonAssignment
                    command={SoundEditorCommands.PIANO_ROLL_VERTICAL_SCALE_REDUCE}
                    vesKeybindingService={services.vesKeybindingService}
                    when={GRAPHICAL_EDITOR_FOCUS_CONTEXT}
                    width={KEYBINDING_WIDTH}
                />
                <ButtonAssignment
                    command={SoundEditorCommands.PIANO_ROLL_VERTICAL_SCALE_INCREASE}
                    vesKeybindingService={services.vesKeybindingService}
                    when={GRAPHICAL_EDITOR_FOCUS_CONTEXT}
                    width={KEYBINDING_WIDTH}
                />
                <ButtonAssignment
                    command={SoundEditorCommands.PIANO_ROLL_VERTICAL_SCALE_RESET}
                    vesKeybindingService={services.vesKeybindingService}
                    when={GRAPHICAL_EDITOR_FOCUS_CONTEXT}
                    width={KEYBINDING_WIDTH}
                />
                <ButtonAssignment
                    command={SoundEditorCommands.PIANO_ROLL_HORIZONTAL_SCALE_REDUCE}
                    vesKeybindingService={services.vesKeybindingService}
                    when={GRAPHICAL_EDITOR_FOCUS_CONTEXT}
                    width={KEYBINDING_WIDTH}
                />
                <ButtonAssignment
                    command={SoundEditorCommands.PIANO_ROLL_HORIZONTAL_SCALE_INCREASE}
                    vesKeybindingService={services.vesKeybindingService}
                    when={GRAPHICAL_EDITOR_FOCUS_CONTEXT}
                    width={KEYBINDING_WIDTH}
                />
                <ButtonAssignment
                    command={SoundEditorCommands.PIANO_ROLL_HORIZONTAL_SCALE_RESET}
                    vesKeybindingService={services.vesKeybindingService}
                    when={GRAPHICAL_EDITOR_FOCUS_CONTEXT}
                    width={KEYBINDING_WIDTH}
                />
            </VContainer>
        </VContainer>
    );
}
