export enum VesTouchBarCommands {
    init = 'touchbar-init',
    changeViewMode = 'touchbar-change-view-mode',
    setViewMode = 'touchbar-set-view-mode',
    changeBuildIsQueued = 'touchbar-change-build-is-queued',
    changeBuildMode = 'touchbar-change-build-mode',
    changeBuildStatus = 'touchbar-change-build-status',
    changeConnectedFlashCart = 'touchbar-change-connected-flash-cart',
    changeEmulator = 'touchbar-change-emulator',
    changeEmulatorConfigs = 'touchbar-change-emulator-configs',
    changeIsExportQueued = 'touchbar-change-is-export-queued',
    changeIsFlashing = 'touchbar-change-is-flashing',
    onDidChangeFlashingProgress = 'touchbar-change-flashing-progress',
    changeIsFlashQueued = 'touchbar-change-is-flash-queued',
    changeIsRunQueued = 'touchbar-change-is-run-queued',
    executeCommand = 'touchbar-execute-command',
    setBuildMode = 'touchbar-set-build-mode',
    setEmulator = 'touchbar-set-emulator',
}
