name: Build & Package

on:
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.os }}, Node.js v${{ matrix.node }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019, ubuntu-latest, macos-latest]
        node: ["16.x"]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # To fetch all history for all branches and tags. (Will be required for caching with lerna: https://github.com/markuplint/markuplint/pull/111)

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          registry-url: "https://registry.npmjs.org"

      - name: Use Python 3.x
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Build and package
        shell: bash
        run: |
          yarn --skip-integrity-check --network-timeout 100000
          yarn electron package
        env:
          NODE_OPTIONS: --max_old_space_size=4096
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # https://github.com/microsoft/vscode-ripgrep/issues/9

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: |
            applications/electron/dist/*.pkg
            applications/electron/dist/*.deb
            applications/electron/dist/*.exe
            applications/electron/dist/*.AppImage
            applications/electron/dist/*.zip
            applications/electron/dist/latest.yml
            applications/electron/dist/latest-mac.yml
            applications/electron/dist/latest-linux.yml

      - name: Lint
        if: matrix.tests != 'skip'
        shell: bash
        run: |
          yarn lint
